name: CD - Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Déclenchement si tu pushes un tag comme v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculatrice:${{ github.ref_name }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/calculatrice:${{ github.ref_name }}
